"""empty message

Revision ID: 1e047da1b2b4
Revises: d9ae5e646e6a
Create Date: 2022-12-03 13:37:27.032564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e047da1b2b4'
down_revision = 'd9ae5e646e6a'
branch_labels = None
depends_on = None


def upgrade():
      op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family')
    # ### end Alembic commands ###
